app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

// API routes
Route::group([
    'domain' => 'api.ep-store.local',
    'prefix' => 'v1',
    'namespace' => 'Api\V1\Controllers',
], function () {

    // Public routes
    Route::group([], function () {

        Route::get('items', [
            'as' => 'api.items.index',
            'uses' => 'ItemController@index',
        ]);
        Route::get('items/{item}', [
            'as' => 'api.items.retrieve',
            'uses' => 'ItemController@retrieve',
        ]);
        Route::get('items/{item}/ratings', [
            'as' => 'api.items.ratings',
            'uses' => 'ItemController@ratings'
        ]);

        Route::get('users/{user}/items', [
            'as' => 'api.users.items',
            'uses' => 'ItemController@allForUser',
        ]);

    });

    // Routes that need to be accessed via SSL, but not authenticated
    Route::group(['middleware' => ['require-ssl']], function () {

        Route::post('register', [
            'as' => 'api.register',
            'uses' => 'RegistrationController@register',
        ]);

    });

    // Routes that require the user to be logged in
    Route::group(
        ['middleware' => ['auth.basic.once', 'require-ssl', 'check-certificate', 'logger']],
        function () {

            Route::get('users/me', [
                'as' => 'api.users.me',
                'uses' => 'UserController@me',
            ]);

            Route::get('users', [
                'as' => 'api.users.index',
                'uses' => 'UserController@index',
            ]);
            Route::get('users/{user}', [
                'as' => 'api.users.retrieve',
                'uses' => 'UserController@retrieve',
            ]);
            Route::post('users', [
                'as' => 'api.users.create',
                'uses' => 'UserController@create',
            ]);
            Route::put('users/{user}', [
                'as' => 'api.users.update',
                'uses' => 'UserController@update',
            ]);
            Route::delete('users/{user}', [
                'as' => 'api.users.delete',
                'uses' => 'UserController@delete',
            ]);

            Route::post('items', [
                'as' => 'api.items.create',
                'uses' => 'ItemController@create',
            ]);
            Route::put('items/{item}', [
                'as' => 'api.items.update',
                'uses' => 'ItemController@update',
            ]);
            Route::delete('items/{item}', [
                'as' => 'api.items.delete',
                'uses' => 'ItemController@delete',
            ]);
            Route::post('items/{item}/upload', [
                'as' => 'api.items.image.upload',
                'uses' => 'ImageController@uploadItemImages'
            ]);
            Route::put('items/{item}/images/{image}', [
                'as' => 'api.items.image.update',
                'uses' => 'ImageController@updateItemImage'
            ]);
            Route::delete('items/{item}/images/{image}', [
                'as' => 'api.items.image.delete',
                'uses' => 'ImageController@removeItemImage'
            ]);

            Route::post('items/{item}/ratings', [
                'as' => 'api.items.ratings.create',
                'uses' => 'ItemController@createRating',
            ]);
            Route::put('items/{item}/ratings/{rating}', [
                'as' => 'api.items.ratings.update',
                'uses' => 'ItemController@updateRating',
            ]);
            Route::delete('items/{item}/ratings/{rating}', [
                'as' => 'api.items.ratings.delete',
                'uses' => 'ItemController@deleteRating',
            ]);

            Route::get('cart', [
                'as' => 'api.cart.index',
                'uses' => 'CartController@index',
            ]);
            Route::post('cart/{item}', [
                'as' => 'api.cart.addItem',
                'uses' => 'CartController@addItem',
            ]);
            Route::put('cart/{item}', [
                'as' => 'api.cart.updateItem',
                'uses' => 'CartController@updateItem',
            ]);
            Route::delete('cart/{item}', [
                'as' => 'api.cart.removeItem',
                'uses' => 'CartController@removeItem',
            ]);

            Route::get('orders', [
                'as' => 'api.orders.index',
                'uses' => 'OrderController@index',
            ]);
            Route::post('orders', [
                'as' => 'api.orders.create',
                'uses' => 'OrderController@createOrder',
            ]);
            Route::put('orders/{order}/status', [
                'as' => 'api.orders.updateStatus',
                'uses' => 'OrderController@updateOrderStatus',
            ]);

            Route::get('logs/{user}', [
                'as' => 'api.logs.user',
                'uses' => 'UserLogController@user'
            ]);

    });

});

// WEB routes
Route::group([
    'domain' => 'ep-store.local',
    'namespace' => 'Web\Controllers',
    'middleware' => ['csrf']
], function () {

    Route::get('/', function () {
        return redirect()->route('web.items.index');
    });

    // Routes that need to be accessed via SSL
    Route::group(['middleware' => ['require-ssl']], function () {

        Route::get('login', [
            'as' => 'web.login',
            'uses' => 'Auth\AuthController@getLogin',
        ]);
        Route::post('login', [
            'as' => 'web.login.post',
            'uses' => 'Auth\AuthController@postLogin',
        ]);
        Route::get('logout', [
            'as' => 'web.logout',
            'uses' => 'Auth\AuthController@getLogout',
        ]);

        Route::get('register', [
            'as' => 'web.register',
            'uses' => 'Auth\AuthController@getRegister',
        ]);
        Route::post('register', [
            'as' => 'web.register.post',
            'uses' => 'Auth\AuthController@postRegister',
        ]);

    });

    // Routes that require the user to be logged in
    Route::group(
        ['middleware' => ['auth', 'require-ssl', 'check-certificate', 'logger']],
        function () {

            Route::get('selling', [
                'as' => 'web.selling.index',
                'uses' => 'ItemController@allForUser',
            ]);
            Route::get('items/new', [
                'as' => 'web.items.new',
                'uses' => 'ItemController@add',
            ]);
            Route::post('items', [
                'as' => 'web.items.create',
                'uses' => 'ItemController@create',
            ]);
            Route::get('items/{item}/edit', [
                'as' => 'web.items.edit',
                'uses' => 'ItemController@edit',
            ]);
            Route::put('items/{item}', [
                'as' => 'web.items.update',
                'uses' => 'ItemController@update',
            ]);

            Route::get('items/{item}/images', [
                'as' => 'web.items.images.index',
                'uses' => 'ImageController@index',
            ]);
            Route::get('items/{item}/images/new', [
                'as' => 'web.items.images.create',
                'uses' => 'ImageController@create',
            ]);
            Route::post('items/{item}/images', [
                'as' => 'web.items.images.store',
                'uses' => 'ImageController@store',
            ]);
            Route::delete('items/{item}/images/{image}', [
                'as' => 'web.items.images.delete',
                'uses' => 'ImageController@destroy',
            ]);
            Route::get('items/{item}/images/profile', [
                'as' => 'web.items.images.profile',
                'uses' => 'ImageController@selectProfileGet',
            ]);
            Route::put('items/{item}/images/{image}/profile', [
                'as' => 'web.items.images.profile.select',
                'uses' => 'ImageController@selectProfilePost',
            ]);

            Route::post('items/{item}/ratings', [
                'as' => 'web.items.ratings.create',
                'uses' => 'ItemController@createRating',
            ]);
            Route::put('items/{item}/ratings/{rating}', [
                'as' => 'web.items.ratings.update',
                'uses' => 'ItemController@updateRating',
            ]);
            Route::delete('items/{item}/ratings/{rating}', [
                'as' => 'web.items.ratings.delete',
                'uses' => 'ItemController@deleteRating',
            ]);

            Route::get('cart', [
                'as' => 'web.cart.index',
                'uses' => 'CartController@index',
            ]);
            Route::post('cart/{item}', [
                'as' => 'web.cart.addItem',
                'uses' => 'CartController@addItem',
            ]);
            Route::put('cart/{item}', [
                'as' => 'web.cart.updateItem',
                'uses' => 'CartController@updateItemQuantity',
            ]);
            Route::delete('cart/{item}', [
                'as' => 'web.cart.removeItem',
                'uses' => 'CartController@removeItem',
            ]);

            Route::get('orders', [
                'as' => 'web.orders.index',
                'uses' => 'OrderController@index',
            ]);
            Route::get('orders/{order}', [
                'as' => 'web.orders.show',
                'uses' => 'OrderController@show',
            ]);
            Route::put('orders/{order}/status', [
                'as' => 'web.orders.updateStatus',

app/Models/Item.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Collection;

/**
 * Class Item
 *
 * @property int id
 * @property string display
 * @property string description
 * @property float price
 * @property User vendor
 * @property int numRatings
 * @property int numOrders
 * @property mixed averageRating
 * @property Image displayImage
 * @property Collection images
 * @package App\Models
 */
class Item extends Model
{
    /**
     * The database table used by the model.
     *
     * @var string
     */
    protected $table = 'items';

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = ['display', 'description', 'price', 'active'];

    /**
     * The accessors to append to the model's array form.
     *
     * @var array
     */
    protected $appends = ['num_ratings', 'average_rating', 'num_orders', 'display_image_url'];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = ['display_image_id'];

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        'price' => 'float',
        'active' => 'boolean',
    ];

    /**
     * Check wheter the item is active.
     *
     * @return mixed
     */
    public function isActive()
    {
        return $this->active;
    }

    /**
     * Check whether the item is inactive.
     *
     * @return mixed
     */
    public function isInactive()
    {
        return $this->isActive();
    }

    /**
     * Convenient method to access the item vendor directly.
     *
     * @return mixed
     */
    public function getVendorAttribute()
    {
        return $this->vendors()->first();
    }

    /**
     * Get the number of ratings the item has.
     *
     * @return int
     */
    public function getNumRatingsAttribute()
    {
        return $this->ratings()->count();
    }

    /**
     * Get the number of times the item has been bought.
     *
     * @return int
     */
    public function getNumOrdersAttribute()
    {
        return $this->orders()->count();
    }

    /**
     * Get the average rating for the item.
     *
     * @return float
     */
    public function getAverageRatingAttribute()
    {
        return $this->ratings()->get()->avg('rating');
    }

    /**
     * Ge the images for the item.
     *
     * @return mixed
     */
    public function getImagesAttribute()
    {
        return $this->images()->get();
    }

    /**
     * Get the display picture for the item.
     *
     * @return mixed
     */
    public function getDisplayImageAttribute()
    {
        return $this->displayImage()->first();
    }

    /**
     * Get the display image url for the attribute.
     *
     * @return string
     */
    public function getDisplayImageUrlAttribute()
    {
        return $this->displayImage !== null ? $this->displayImage->url : null;
    }

    /**
     * Get an array of all the urls for all the images for the item.
     *
     * @return static
     */
    public function getImagesUrlsAttribute()
    {
        return $this->images->map(function ($image) {
            return $image->url;
        });
    }

    /**
     * Get the directory in which the images for the item are stored.
     *
     * @return string
     */
    public function getImageDirectory()
    {
        return 'item_assets/' . $this->id . '/images/';
    }

    /**
     * Specify that the image urls should be returned with the response.
     *
     * @return $this
     */
    public function withImages()
    {
        $this->appends[] = 'images_urls';
        return $this;
    }

    /**
     * Get the display picture for the item.
     *
     * @return \Illuminate\Database\Eloquent\Relations\HasOne
     */
    public function displayImage()
    {
        return $this->hasOne(Image::class, 'id', 'display_image_id');
    }

    /**
     * All the users that have the item in their carts.
     *
     * @return \Illuminate\Database\Eloquent\Relations\BelongsToMany
     */
    public function userCarts()
    {
        return $this->belongsToMany(User::class, 'cart_items', 'item_id', 'user_id')
            ->withPivot('quantity')
            ->withTimestamps();
    }

    /**
     * The vendor associated with the item.
     *
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function vendors()
    {
        return $this->belongsTo(User::class, 'vendor_id');
    }

    /**
     * All the orders that have been made with the item.
     *
     * @return \Illuminate\Database\Eloquent\Relations\BelongsToMany
     */
    public function orders()
    {
        return $this->hasMany(Order::class);
    }

    /**
     * All the ratings given to the item.
     *
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function ratings()
    {
        return $this->hasMany(Rating::class);
    }

    /**
     * All the images associated with the item.
     *
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function images()
    {
        return $this->hasMany(Image::class);
    }
}

resources/views/items/edit.blade.php
@extends('layouts.master')

@section('title', 'Editing item ' . $item->display)

@section('main-content')
    <div class="panel panel-default">
        <div class="panel-heading">
            <h1>Editing item {{ $item->display }}</h1>
        </div>

        <ul class="list-group">
            <li class="list-group-item">
                <ol class="breadcrumb">
                    <li>{!! link_to_route('web.selling.index', 'Selling') !!}</li>
                    <li>{!! link_to_route('web.items.edit', $item->display, $item->id) !!}</li>
                </ol>
                <div class="row">
                    <div class="col-md-offset-3 col-md-9">
                        <h3>Basic information</h3>
                    </div>
                    {!! Form::model($item, ['route' => ['web.items.update', $item->id], 'method' => 'put', 'class' => 'form-horizontal']) !!}
                    @include('partials.horizontal-form-element', ['field' => 'display'])
                    @include('partials.horizontal-form-element', ['field' => 'description', 'type' => 'textarea'])
                    @include('partials.horizontal-form-element', ['field' => 'price'])

                    <div class="form-group">
                        <div class="col-md-offset-3 col-md-9">
                            <div class="checkbox">
                                <label>
                                    {!! Form::checkbox('active', 1, null) !!} Active
                                </label>
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-md-offset-3 col-md-9">
                            {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
                        </div>
                    </div>
                    {!! Form::close() !!}
                </div>
            </li>

            <li class="list-group-item">
                {!! link_to_route('web.items.images.index', 'Manage item images', [$item->id], ['class' => 'btn btn-default']) !!}
            </li>
        </ul>
    </div>
@stop

resources/views/items/index.blade.php
@extends('layouts.master')

@section('title', 'Items')

@section('main-content')
    <h1>These are the items</h1>

    <h3>Total: {{ $items->total() }}</h3>

    <div class="panel panel-default">
        <div class="panel-body">
            <div class="row">
                <div class="col-md-6">
                    {!! Form::open(['route' => 'web.items.index', 'method' => 'get']) !!}
                    <div class="input-group">
                        <span class="input-group-btn">
                            <button class="btn btn-default" type="submit">Go!</button>
                        </span>
                        <input type="text" class="form-control" placeholder="Search for..." name="query">
                    </div>
                    {!! Form::close() !!}
                </div>
            </div>
            <br>
            <div class="row">
                <div class="col-md-12">
                    <p><b>Sort by:</b></p>
                </div>
                <div class="col-md-12">
                    {!! link_to_route('web.items.index', 'Display asc', ['sort' => 'display.asc']) !!}
                    {!! link_to_route('web.items.index', 'Display desc', ['sort' => 'display.desc']) !!}
                    {!! link_to_route('web.items.index', 'Price asc', ['sort' => 'price.asc']) !!}
                    {!! link_to_route('web.items.index', 'Price desc', ['sort' => 'price.desc']) !!}
                </div>
            </div>
        </div>
    </div>

    @foreach($items as $item)
        <div class="panel panel-default"{{ $item->active ? '' : ' style=opacity:0.75' }}>
            <div class="panel-body row">
                <div class="col-md-2">
                    <a href="{!! route('web.items.retrieve', $item->id) !!}" class="thumbnail">
                        @if($item->displayImage)
                            <img src="{!! $item->displayImage->url !!}" alt="">
                        @else
                            <img src="https://placehold.it/150x150" alt="">
                        @endif
                    </a>
                </div>
                <div class="col-md-10">
                    <h3>{!! link_to_route('web.items.retrieve', $item->display, [$item->id]) !!}</h3>
                    <p>{{ $item->description }}</p>
                    @can('update', $item)
                    {!! link_to_route('web.items.edit', 'Edit', [$item]) !!}
                    @endcan
                </div>
            </div>
        </div>
    @endforeach

    @if($items->total() > $items->perPage())
        <nav>
            <ul class="pagination">
                @if($items->previousPageUrl() or $items->currentPage() !== 1)
                    <li><a href="{!! $items->previousPageUrl() !!}"><span>&laquo;</span></a></li>
                @endif
                {{--*/ $numPages = ceil($items->total() / $items->perPage()) /*--}}
                @for($i = 1; $i <= $numPages; ++$i)
                    <li{{ $i === $items->currentPage() ? ' class=active' : '' }}>
                        <a href="{!! $items->url($i) !!}">{{ $i }}</a>
                    </li>
                @endfor
                @if($items->nextPageUrl())
                    <li><a href="{!! $items->nextPageUrl() !!}"><span>&raquo;</span></a></li>
                @endif
            </ul>
        </nav>
    @endif
@stop

resources/views/items/new.blade.php
@extends('layouts.master')

@section('title', 'Adding a new item')

@section('main-content')
    <div class="panel panel-default">
        <div class="panel-heading">
            <h1>Add a new item</h1>
        </div>

        <ul class="list-group">
            <li class="list-group-item">
                <ol class="breadcrumb">
                    <li>{!! link_to_route('web.selling.index', 'Selling') !!}</li>
                    <li>{!! link_to_route('web.items.new', 'New item') !!}</li>
                </ol>
                <div class="row">
                    <div class="col-md-offset-3 col-md-9">
                        <h3>Basic information</h3>
                    </div>
                    {!! Form::open(['route' => 'web.items.create', 'class' => 'form-horizontal']) !!}
                    @include('partials.horizontal-form-element', ['field' => 'display'])
                    @include('partials.horizontal-form-element', ['field' => 'description', 'type' => 'textarea'])
                    @include('partials.horizontal-form-element', ['field' => 'price'])

                    <div class="form-group">
                        <div class="col-md-offset-3 col-md-9">
                            <div class="checkbox">
                                <label>
                                    {!! Form::checkbox('active', 1, null) !!} Active
                                </label>
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-md-offset-3 col-md-9">
                            {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
                        </div>
                    </div>
                    {!! Form::close() !!}
                </div>
            </li>
        </ul>
    </div>
@stop

resources/views/items/selling.blade.php
@extends('layouts.master')

@section('title', 'Items')

@section('main-content')
    <h1>Selling</h1>

    <h3>Total: {{ $items->total() }}</h3>

    {!! link_to_route('web.items.new', 'Add a new item') !!}

    @foreach($items as $item)
        <div class="panel panel-default"{{ $item->active ? '' : ' style=opacity:0.75' }}>
            <div class="panel-body row">
                <div class="col-md-2">
                    <a href="{!! route('web.items.retrieve', $item->id) !!}" class="thumbnail">
                        @if($item->displayImage)
                            <img src="{!! $item->displayImage->url !!}" alt="">
                        @else
                            <img src="https://placehold.it/150x150" alt="">
                        @endif
                    </a>
                </div>
                <div class="col-md-10">
                    <h3>{!! link_to_route('web.items.retrieve', $item->display, [$item->id]) !!}</h3>
                    <p>{{ $item->description }}</p>
                    @can('update', $item)
                    {!! link_to_route('web.items.edit', 'Edit', [$item]) !!}
                    @endcan
                </div>
            </div>
        </div>
    @endforeach

    @if($items->total() > $items->perPage())
        <nav>
            <ul class="pagination">
                @if($items->previousPageUrl() or $items->currentPage() !== 1)
                    <li><a href="{!! $items->previousPageUrl() !!}"><span>&laquo;</span></a></li>
                @endif
                {{--*/ $numPages = ceil($items->total() / $items->perPage()) /*--}}
                @for($i = 1; $i <= $numPages; ++$i)
                    <li{{ $i === $items->currentPage() ? ' class=active' : '' }}>
                        <a href="{!! $items->url($i) !!}">{{ $i }}</a>
                    </li>
                @endfor
                @if($items->nextPageUrl())
                    <li><a href="{!! $items->nextPageUrl() !!}"><span>&raquo;</span></a></li>
                @endif
            </ul>
        </nav>
    @endif
@stop

resources/views/items/show.blade.php
@extends('layouts.master')

@section('title', $item->display)

@section('main-content')


    <div class="panel panel-default"{{ $item->active ? '' : ' style=opacity:0.75' }}>
        <ul class="list-group">

            <li class="list-group-item row">
                <div class="col-md-3">
                    <img src="{{ $item->display_image ?
                URL::asset($item->getImageDirectory() . $item->display_image->name) :
                'https://placehold.it/200x200' }}" alt="" width="100%" class="img-thumbnail">
                </div>
                <div class="col-md-9">
                    <h1>{{ $item->display }}</h1>
                    <p>{{ $item->description }}</p>
                    <em>{{ $item->price }}&nbsp;&euro;</em>
                    <br>
                    <b>Rating:
                        @if($item->numRatings > 0)
                            {{ number_format((float)$item->averageRating, 1, '.', '') }}
                            (rated {{ $item->numRatings }} times)
                        @else
                            <i>This item has not been rated yet.</i>
                        @endif
                    </b>

                    @if(Auth::check() and Auth::user()->owns($item))
                        {!! link_to_route('web.items.edit', 'Edit', $item->id, ['class' => 'btn btn-default']) !!}
                    @endif

                    @if(Auth::check())
                        {!! Form::open(['route' => ['web.items.ratings.create', $item->id], 'class' => 'form-inline']) !!}
                        <div class="input-group">
                            {!! Form::text('rating', '', ['class' => 'form-control', 'size' => 3]) !!}
                            <span class="input-group-btn">
                            {!! Form::submit('Rate', ['class' => 'btn btn-default']) !!}
                        </span>
                        </div>
                        {!! Form::close() !!}
                    @else
                        <p><i>You must be logged in to rate items.</i></p>
                    @endif

                    <br>

                    @if(Auth::check() and !Auth::user()->hasItemInCart($item))
                        {!! Form::open(['route' => ['web.cart.addItem', $item->id], 'class' => 'form-inline']) !!}
                        <div class="input-group">
                            {!! Form::text('quantity', 1, ['class' => 'form-control', 'size' => 3]) !!}
                            <span class="input-group-btn">
                            {!! Form::submit('Add to cart', ['class' => 'btn btn-default']) !!}
                            </span>
                        </div>
                        {!! Form::close() !!}
                    @elseif(Auth::check())
                        <p><i>You already have this item in your cart.</i></p>
                    @else
                        <p><i>You must be logged in to add items to your cart.</i></p>
                    @endif
                </div>
            </li>
            <li class="list-group-item row">
                <div class="col-md-12">
                    <h3>Image gallery</h3>
                </div>
                @foreach($item->images as $image)
                    <div class="col-md-3">
                        <img src="{{
                            URL::asset($item->getImageDirectory() . $image->name)
                        }}" alt="" width="100%" class="img-thumbnail">
                    </div>
                @endforeach
                @if($item->images->isEmpty())
                    <div class="col-md-12">
                        <i>No pictures have yet been added.</i>
                    </div>
                @endif
            </li>

            <li class="list-group-item row">
                <div class="col-md-12">
                    <h3>Reviews</h3>
                </div>
                @foreach($item->ratings as $rating)
                    @if($rating->review)
                        <div class="col-md-12">
                            <p><b>{{ $rating->user->name }}</b> rated this item
                                with {{ $rating->rating}}
                            </p>
                            <p>{{ $rating->review }}</p>
                        </div>
                    @endif
                @endforeach
                @if($item->ratings->filter(function ($r) { return $r->review !== '' and $r->review !== null; })->isEmpty())
                    <div class="col-md-12">
                        <p><i>This item doesn't have any reviews yet.</i></p>
                    </div>
                @endif
            </li>

        </ul>
    </div>
@stop